FROM python:3.6.2-alpine3.6

WORKDIR /src

COPY requirements.txt requirements.txt

RUN  apk add --no-cache -t build-deps gcc musl-dev \
     && pip install --no-cache-dir -r requirements.txt \
     && apk del build-deps


WORKDIR /src/notifications/web

COPY web/package.json package.json
COPY web/package-lock.json package-lock.json
RUN apk add --no-cache -t build-deps nodejs-npm \
    && npm install


COPY web/dist dist
COPY web/src src
COPY web/webpack.config.js webpack.config.js
RUN npm run build

WORKDIR /src
COPY . notifications

CMD ["python", "-m", "notifications"]
